name: Package Java WAR into RPM

on:
  #  release:
  #   types:
  #    - created
  workflow_dispatch:
  pull_request:
    branches: [ master ]

env:
  HEALTH_WAIT_TIME: 200
  TEST_IMAGE_NAME: 'local/rhel8-jboss-java17-webserver5'

jobs:
  prepare_docker_images:
    name: Build ${{ matrix.docker_file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_file: [ dockerfile-rhel8 ]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Build Java WAR
        run: mvn clean package -DskipTests

      - name: Get mvn project.version
        run: |
          projectVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT/.SNAPSHOT/g')
          echo "ORS_VERSION=$projectVersion" >> "$GITHUB_ENV"

      - name: RPMBuild
        id: rpmbuild
        run: |
          # Define the RPM build directory
          export RPM_BUILD_DIR=$HOME/rpmbuild
          echo "RPM_BUILD_DIR=$RPM_BUILD_DIR"
          # Install RPM
          sudo apt-get install rpm
          # Clean the RPM build directory
          rm -rf $RPM_BUILD_DIR
          # Create the RPM build directory structure from scratch
          mkdir -p $RPM_BUILD_DIR/{BUILD,RPMS,SPECS,SRPMS}
          cp -f ${{ github.workspace }}/ors-api/target/ors.war $RPM_BUILD_DIR/BUILD/
          rpmbuild -bb ${{ github.workspace }}/.rpm-packaging/ors-war.spec
          # Copy the RPM package to the workspace
          cp -f $RPM_BUILD_DIR/RPMS/noarch/*.rpm ${{ github.workspace }}/ors.rpm
          # Save the RPM package name as an step output
          echo "RPM_PATH=${{ github.workspace }}/ors.rpm" >> "$GITHUB_ENV"

      - name: Prepare the graph environment
        run: |
          cp ors-api/src/test/files/elevation/srtm_38_03.gh .rpm-packaging/
          cp ors-api/src/test/files/heidelberg.osm.gz .rpm-packaging/

      - name: Login to RedHat Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_LOGIN }}
          password: ${{ secrets.REDHAT_REGISTRY_PASSWORD }}

      - name: Build rpm test image for dockerfile ${{ matrix.docker_file }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .rpm-packaging/${{ matrix.docker_file }}
          push: false
          load: false
          tags: ${{ env.TEST_IMAGE_NAME }}-${{ matrix.docker_file }}:latest
          build-args: |
            REDHAT_ORG=${{ secrets.REDHAT_ORG }}
            REDHAT_ACTIVATION_KEY_NAME=${{ secrets.REDHAT_ACTIVATION_KEY_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Load the rpm test image from cache ${{ matrix.docker_file }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .rpm-packaging/${{ matrix.docker_file }}
          push: false
          load: true
          tags: ${{ env.TEST_IMAGE_NAME }}-${{ matrix.docker_file }}:latest
          build-args: |
            REDHAT_ORG=${{ secrets.REDHAT_ORG }}
            REDHAT_ACTIVATION_KEY_NAME=${{ secrets.REDHAT_ACTIVATION_KEY_NAME }}
          cache-from: type=gha
      - name: Run and test the docker image
        run: |
          echo "Waiting for the docker container to start"
          # Run the pre-build docker image and mount the needed files
          # Mount the elevation file to avoid downloading it
          # Mount the osm pbf file for the graph build
          # Mount the special ors-config.json file for the rpm container
          docker run -it -d -p 8080:8080 --name ors-rpm-testing \
            -v $(pwd)/ors-api/src/test/files/elevation/srtm_38_03.gh:/opt/openrouteservice/.elevation-cache/srtm_38_03.gh \
            -v $(pwd)/ors-api/src/test/files/heidelberg.osm.gz:/opt/openrouteservice/files/osm-file.osm.gz  \
            -v $(pwd)/.rpm-packaging/ors-config.json:/opt/openrouteservice/config/ors-config.json \
            -v $RPM_PATH:/tmp/ors.rpm \
            ${{ env.TEST_IMAGE_NAME }}-${{ matrix.docker_file }}:latest
          
          ##### Check a clean environment #####
          # Check that the rpm package is not installed and fail if it is
          docker exec -u root ors-rpm-testing sh -c "rpm -q openrouteservice" && exit 1 || echo "openrouteservice is not installed"
          # Check that the folder /opt/openrouteservice doesn't exist and fail if it does
          docker exec -u root ors-rpm-testing sh -c "ls /opt/openrouteservice" && exit 1 || echo "/opt/openrouteservice doesn't exist"
          # Check that the folder webapps/ors doesn't exist and fail if it does
          docker exec -u root ors-rpm-testing sh -c 'ls ${JWS_HOME}/webapps/ors' && exit 1 || echo "webapps/ors doesn't exist"
          # Check that the folder webapps/ors.war doesn't exist and fail if it does
          docker exec -u root ors-rpm-testing sh -c 'ls ${JWS_HOME}/webapps/ors.war' && exit 1 || echo "webapps/ors.war doesn't exist"
          
          ##### Install the rpm package #####
          # Create the missing jws5* rpm packages with fakeprovide
          docker exec -u root ors-rpm-testing fakeprovide jws5-runtime
          docker exec -u root ors-rpm-testing fakeprovide jws5-tomcat
          docker exec -u root ors-rpm-testing fakeprovide jws5-tomcat-native
          docker exec -u root ors-rpm-testing fakeprovide jws5-tomcat-selinux
          # List the fakeprovide packages
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS | grep fakeprovide"
          # Install the rpm package as root with the fakeprovide packages
          docker exec -u root ors-rpm-testing sh -c 'yum install -y fakeprovide-jws5-* /tmp/ors.rpm'
          
          ##### Test installation process was successful #####
          # Check that the rpm package is installed and fail if $? is not 0
          docker exec -u root ors-rpm-testing sh -c "rpm -q openrouteservice" || exit 1 && echo "openrouteservice is installed"
          # Check that the ors-config.json file is in it's place in /opt/openrouteservice/config/ors-config.json
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/config/ors-config.json" || exit 1
          # Check that the elevation file is in it's place in /opt/openrouteservice/.elevation-cache/srtm_38_03.gh
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/.elevation-cache/srtm_38_03.gh" || exit 1
          # Check that the osm pbf file is in it's place in /opt/openrouteservice/files/osm-file.osm.gz
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/files/osm-file.osm.gz" || exit 1
          # Check that the war file is in it's place in /tmp/ors.war
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /tmp/ors.war" || exit 1
          # Check ${JWS_HOME}/webapps folder is created
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS ${JWS_HOME}/webapps" || exit 1
          # Check /opt/openrouteservice/ contains the following folders: config, logs, .war-files, .elevation-cache, files, graphs
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/" || exit 1
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/config" || exit 1
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/logs" || exit 1
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/.war-files" || exit 1
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/.elevation-cache" || exit 1
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/files" || exit 1
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/graphs" || exit 1
          # Check /opt/openrouteservice/.war-files/$ORS_VERSION_ors.war exists
          docker exec -u root ors-rpm-testing sh -c "ls -sahlS /opt/openrouteservice/.war-files/$ORS_VERSION_ors.war"
          # Check ${JWS_HOME}/webapps/ doesn't contain a folder called ors after the installation
          docker exec -u root ors-rpm-testing sh -c 'ls -sahlS ${JWS_HOME}/webapps' | grep ors && exit 1 || echo "webapps/ors doesn't exist"
          # Check ${JWS_HOME}/webapps/ors.war is a symlink to /opt/openrouteservice/.war-files/$ORS_VERSION_ors.war
          docker exec -u root ors-rpm-testing sh -c 'if [ -L ${JWS_HOME}/webapps/ors.war ]; then exit 0; else exit 1; fi' && echo "Symlink exists" || echo exit 1
          # Check the group openrouteservice exists
          docker exec -u root ors-rpm-testing sh -c "getent group openrouteservice" || exit 1
          # Check the user openrouteservice and jboss exist
          docker exec -u root ors-rpm-testing sh -c "getent passwd openrouteservice jboss" || exit 1
          # Check the users openrouteservice and jboss are in the group openrouteservice
          docker exec -u root ors-rpm-testing sh -c "getent group openrouteservice | grep openrouteservice | grep jboss" || exit 1
          # Check that ${JWS_HOME}/bin/setenv.sh contains export ORS_CONFIG=/opt/openrouteservice/config/ors-config.json
          docker exec -u root ors-rpm-testing sh -c 'cat ${JWS_HOME}/bin/setenv.sh | grep ORS_CONFIG=/opt/openrouteservice/config/ors-config.json' || exit 1
          # Check that the default java is java-17-openjdk
          docker exec -u root ors-rpm-testing sh -c 'java -version 2>&1 | grep "openjdk version \"17"' || exit 1'
          # Check that the number of folders in /opt/openrouteservice/ owned by user and group openrouteservice is 7
          docker exec -u root ors-rpm-testing sh -c 'find /opt/openrouteservice/ -type d -user openrouteservice -group openrouteservice | wc -l | grep 7' || exit 1
          # Check that the number of files in /opt/openrouteservice/ owned by user and group openrouteservice is 4
          docker exec -u root ors-rpm-testing sh -c 'find /opt/openrouteservice/ -type f -user openrouteservice -group openrouteservice | wc -l | grep 4' || exit 1
          # Check that the number of files and folders in /opt/openrouteservice/ owned by some other user is 0
          docker exec -u root ors-rpm-testing sh -c 'find /opt/openrouteservice/ -not -user openrouteservice | wc -l | grep 0' || exit 1
          # Check that the number of files and folders in /opt/openrouteservice/ owned by some other group is 0
          docker exec -u root ors-rpm-testing sh -c 'find /opt/openrouteservice/ -not -group openrouteservice | wc -l | grep 0' || exit 1
          
          # Restart the container to load the new configuration
          docker restart ors-rpm-testing
          
          # echo "Waiting for the docker container to build graphs and return 200"
          # .github/utils/url_check.sh 127.0.0.1 8080 /ors/v2/health 200 ${{ env.HEALTH_WAIT_TIME }}
          echo "Print docker logs"
          docker logs ors-rpm-testing

#      - name: Attach RPM package to release
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ~/rpmbuild/RPMS/noarch/my-app-1.0.0-1.noarch.rpm
#          asset_name: my-app-1.0.0-1.noarch.rpm
#          asset_content_type: application/x-rpm