name: Package Java WAR into RPM

on:
  #  release:
  #   types:
  #    - created
  workflow_dispatch:
  pull_request:
    branches: [ v7.2.* ]
  push:
    branches: [ v7.2.* ]
env:
  HEALTH_WAIT_TIME: 200
  TEST_IMAGE_NAME: 'local/rhel8-jboss-java17-webserver5'

jobs:
  prepare_docker_images:
    name: Build ${{ matrix.docker_file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_file: [ dockerfile-jboss-java17-rhel8 ]
    env:
      CONTAINER_NAME: ${{ matrix.docker_file }}
      IMAGE_NAME: local/${{ matrix.docker_file }}:latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Build Java WAR
        run: mvn clean package -DskipTests

      - name: Get mvn project.version
        run: |
          projectVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT/.SNAPSHOT/g')
          echo "ORS_VERSION=$projectVersion" >> "$GITHUB_ENV"

      - name: RPMBuild
        id: rpmbuild
        run: |
          # Define the RPM build directory
          export RPM_BUILD_DIR=$HOME/rpmbuild
          echo "RPM_BUILD_DIR=$RPM_BUILD_DIR"
          # Install RPM
          sudo apt-get install rpm
          # Clean the RPM build directory
          rm -rf $RPM_BUILD_DIR
          # Create the RPM build directory structure from scratch
          mkdir -p $RPM_BUILD_DIR/{BUILD,RPMS,SPECS,SRPMS}
          cp -f ${{ github.workspace }}/ors-api/target/ors.war $RPM_BUILD_DIR/BUILD/
          rpmbuild -bb ${{ github.workspace }}/.rpm-packaging/ors-war.spec
          # Copy the RPM package to the workspace
          cp -f $RPM_BUILD_DIR/RPMS/noarch/*.rpm ${{ github.workspace }}/ors.rpm
          # Save the RPM package name as an step output
          echo "RPM_PATH=${{ github.workspace }}/ors.rpm" >> "$GITHUB_ENV"

      - name: Import the GPG key
        uses: MichaelsJP/ghaction-import-gpg@v1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}

      - name: Prepare the signing environment
        run: |
          echo "Paste the GPG key fingerprint to the ~/.rpmmacros file"
          cat > ~/.rpmmacros << EOF
          %_signature gpg
          %_gpg_name ${{ secrets.GPG_FINGERPRINT }}
          EOF
          
          echo "List loaded gpg keys in store"
          gpg --list-secret-keys
          echo "Import the public GPG key to rpm"
          gpg --export --armor ${{ secrets.GPG_FINGERPRINT }} > public_key.asc
          rpm --import public_key.asc
          echo "List loaded gpg keys in rpm"
          rpm --query --all | grep --ignore-case gpg
          # Export the key path to the environment
          echo "GPG_KEY_PATH=$(realpath public_key.asc)" >> "$GITHUB_ENV"

      - name: Sign the RPM package
        run: |
          rpm --addsign ${{ env.RPM_PATH }}
          # Print signature details
          rpm --query -pi ${{ env.RPM_PATH }}
          # Verify the signature and fail if it is not valid
          rpm --checksig ${{ env.RPM_PATH }}
          if [ $? -ne 0 ]; then
            echo "RPM signature is not valid"
            exit 1
          fi
      - name: Prepare the graph environment
        run: |
          cp ors-api/src/test/files/elevation/srtm_38_03.gh .rpm-packaging/
          cp ors-api/src/test/files/heidelberg.osm.gz .rpm-packaging/

      - name: Login to RedHat Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_LOGIN }}
          password: ${{ secrets.REDHAT_REGISTRY_PASSWORD }}

      - name: Build rpm image for dockerfile ${{ matrix.docker_file }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .rpm-packaging/${{ matrix.docker_file }}
          push: false
          load: false
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            REDHAT_ORG=${{ secrets.REDHAT_ORG }}
            REDHAT_ACTIVATION_KEY_NAME=${{ secrets.REDHAT_ACTIVATION_KEY_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Load the rpm test image from cache ${{ matrix.docker_file }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .rpm-packaging/${{ matrix.docker_file }}
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            REDHAT_ORG=${{ secrets.REDHAT_ORG }}
            REDHAT_ACTIVATION_KEY_NAME=${{ secrets.REDHAT_ACTIVATION_KEY_NAME }}
          cache-from: type=gha

      - name: Setup the docker container
        shell: bash
        run: |
          echo "Waiting for the docker container to start"
          # Run the pre-build docker image and mount the needed files
          # Mount the elevation file to avoid downloading it
          # Mount the osm pbf file for the graph build
          # Mount the special ors-config.json file for the rpm container
          docker run -it -d -p 8080:8080 --name ${{ env.CONTAINER_NAME }} \
            -v $(pwd)/ors-api/src/test/files/elevation/srtm_38_03.gh:/opt/openrouteservice/.elevation-cache/srtm_38_03.gh \
            -v $(pwd)/ors-api/src/test/files/heidelberg.osm.gz:/opt/openrouteservice/files/osm-file.osm.gz  \
            -v $(pwd)/.rpm-packaging/ors-config.json:/opt/openrouteservice/config/ors-config.json \
            -v ${{ env.RPM_PATH }}:/tmp/ors.rpm \
            -v ${{ env.GPG_KEY_PATH }}:/tmp/public_key.asc \
            ${{ env.IMAGE_NAME }}

      - name: Check the pre-install environment
        shell: bash
        run: |
          ##### Check the pre install environment #####
          echo "Checking the pre install environment"
          bash ${{ github.workspace }}/.rpm-packaging/rhel8_pre_install_check.sh

      - name: Install the rpm package
        shell: bash
        run: |
          ##### Import the GPG key #####
          echo "Importing the GPG key inside the docker container"
          docker exec -u root ${{ env.CONTAINER_NAME }} rpm --import /tmp/public_key.asc

          ##### Install the rpm package #####
          echo "Installing the rpm package"
          # Create the missing jws5* rpm packages with fakeprovide
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-runtime
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-tomcat
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-tomcat-native
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-tomcat-selinux
          # List the fakeprovide packages
          docker exec -u root ${{ env.CONTAINER_NAME }} sh -c "ls -sahlS | grep fakeprovide"
          # Install the rpm package as root with the fakeprovide packages
          docker exec -u root ${{ env.CONTAINER_NAME }} sh -c 'yum install -y fakeprovide-jws5-* /tmp/ors.rpm'
          
          ##### Check the post install environment #####
          echo "Checking the post install environment"
          bash ${{ github.workspace }}/.rpm-packaging/rhel8_post_install_check.sh

      - name: Test the graph building
        shell: bash
        run: |
          ##### Start the graph building #####
          # Restart the container to load the new configuration
          docker restart ${{ env.CONTAINER_NAME }}
          
          # echo "Waiting for the docker container to build graphs and return 200"
          .github/utils/url_check.sh 127.0.0.1 8080 /ors/v2/health 200 ${{ env.HEALTH_WAIT_TIME }}
          echo "Print docker logs"
          docker logs ${{ env.CONTAINER_NAME }}

      - name: Print the container logs
        shell: bash
        run: |
          ##### Print the container logs #####
          echo "Print docker logs"
          docker logs ${{ env.CONTAINER_NAME }}

      - name: Uninstall the rpm package
        shell: bash
        run: |
          ##### Uninstall the rpm package #####
          echo "Uninstalling the rpm package"
          docker exec -u root ${{ env.CONTAINER_NAME }} sh -c 'yum remove -y openrouteservice'
          
          ##### Check the post uninstall environment #####
          echo "Checking the post uninstall environment"
          bash ${{ github.workspace }}/.rpm-packaging/rhel8_post_uninstall_check.sh

      - name: Clean the public GPG key
        run: |
          rm -f ${{ env.GPG_KEY_PATH }}
#      - name: Attach RPM package to release
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ~/rpmbuild/RPMS/noarch/my-app-1.0.0-1.noarch.rpm
#          asset_name: my-app-1.0.0-1.noarch.rpm
#          asset_content_type: application/x-rpm