name: Package Java WAR into RPM with JBoss Web Server 5

on:
  release:
    types: [ created ]
    branches: [ releases/v7.2.* ]
  workflow_dispatch:
  pull_request:
    branches: [ releases/v7.2.* ]
  push:
    branches: [ releases/v7.2.* ]
env:
  HEALTH_WAIT_TIME: 200
  RPM_TESTING_REPO_WAIT_TIME: 60
  TEST_IMAGE_NAME: 'local/rhel8-jboss-java17-webserver5'
  RPM_REPO_TESTING_URL: '${{ secrets.NEXUS_URL }}/repository/openrouteservice-rpm/testing'
  RPM_REPO_SNAPSHOTS_URL: '${{ secrets.NEXUS_URL }}/repository/openrouteservice-rpm/snapshots'
  RPM_REPO_RELEASES_URL: '${{ secrets.NEXUS_URL }}/repository/openrouteservice-rpm/releases'

jobs:
  prepare_docker_images:
    name: Build ${{ matrix.docker_file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_file: [ dockerfile-jboss-java17-rhel8 ]
    env:
      CONTAINER_NAME: ${{ matrix.docker_file }}
      IMAGE_NAME: local/${{ matrix.docker_file }}:latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Build Java WAR
        run: mvn clean package -DskipTests

      - name: Get mvn project.version
        run: |
          projectVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT/.SNAPSHOT/g')
          echo "ORS_VERSION=$projectVersion" >> "$GITHUB_ENV"

      - name: Extract branch name and set the rpm snapshots and testing repository urls
        id: snapshots_and_testing_urls
        shell: bash
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          # Replace all slashes and underscores with dashes
          branch=${branch//[\/_]/-}
          # Remove all characters except underscores and alphanumeric characters 
          branch=${branch//[^a-zA-Z0-9_-]/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          # Set the testing and snapshot repository url
          echo "rpm_repo_testing_url=${{ env.RPM_REPO_TESTING_URL }}/$branch/noarch" >> $GITHUB_OUTPUT
          echo "rpm_repo_snapshots_url=${{ env.RPM_REPO_SNAPSHOTS_URL }}/$branch/noarch" >> $GITHUB_OUTPUT

      - name: Build the RPM package
        id: rpmbuild
        run: |
          # Define the RPM build directory
          export RPM_BUILD_DIR=$HOME/rpmbuild
          echo "RPM_BUILD_DIR=$RPM_BUILD_DIR"
          # Install RPM
          sudo apt-get install rpm
          # Clean the RPM build directory
          rm -rf $RPM_BUILD_DIR
          # Create the RPM build directory structure from scratch
          mkdir -p $RPM_BUILD_DIR/{BUILD,RPMS,SPECS,SRPMS}
          cp -f ${{ github.workspace }}/ors-api/target/ors.war $RPM_BUILD_DIR/BUILD/
          rpmbuild -bb ${{ github.workspace }}/.rpm-packaging/ors-war.spec
          
          # Save the RPM package name and path as an step output
          export rpm_name=openrouteservice-${{ env.ORS_VERSION }}-jws5-el8-noarch.rpm
          export rpm_path=${{ github.workspace }}/$rpm_name
          echo "RPM_NAME=$rpm_name" >> "$GITHUB_ENV"
          echo "RPM_PATH=$rpm_path" >> "$GITHUB_ENV"
          
          # Copy the RPM package to the workspace
          cp -f $RPM_BUILD_DIR/RPMS/noarch/*.rpm $rpm_path

      - name: Import the GPG key
        uses: MichaelsJP/ghaction-import-gpg@v1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}

      - name: Prepare the signing environment
        run: |
          echo "Paste the GPG key fingerprint to the ~/.rpmmacros file"
          cat > ~/.rpmmacros << EOF
          %_signature gpg
          %_gpg_name ${{ secrets.GPG_FINGERPRINT }}
          EOF
          
          echo "List loaded gpg keys in store"
          gpg --list-secret-keys
          echo "Import the public GPG key to rpm"
          gpg --export --armor ${{ secrets.GPG_FINGERPRINT }} > public_key.asc
          rpm --import public_key.asc
          echo "List loaded gpg keys in rpm"
          rpm --query --all | grep --ignore-case gpg
          # Export the key path to the environment
          echo "GPG_KEY_PATH=$(realpath public_key.asc)" >> "$GITHUB_ENV"

      - name: Sign the RPM package
        run: |
          rpm --addsign ${{ env.RPM_PATH }}
          # Print signature details
          rpm --query -pi ${{ env.RPM_PATH }}
          # Verify the signature and fail if it is not valid
          rpm --checksig ${{ env.RPM_PATH }}
          if [ $? -ne 0 ]; then
            echo "RPM signature is not valid"
            exit 1
          fi    

      - name: Upload the testing RPM
        run: |
          # Upload the RPM package to the testing repository and only use -v if github.debug is true

          curl -v -u '${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}' \
            --upload-file '${{ env.RPM_PATH }}' '${{ steps.snapshots_and_testing_urls.outputs.rpm_repo_testing_url }}/${{ env.RPM_NAME }}'

          # Validate curls exit code
          if [ $? -ne 0 ]; then
              echo "Failed to upload the RPM package to the testing repository"
              exit 1
          fi

      - name: Login to RedHat Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_LOGIN }}
          password: ${{ secrets.REDHAT_REGISTRY_PASSWORD }}

      - name: Build and load the rpm image for dockerfile ${{ matrix.docker_file }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .rpm-packaging/${{ matrix.docker_file }}
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            REDHAT_ORG=${{ secrets.REDHAT_ORG }}
            REDHAT_ACTIVATION_KEY_NAME=${{ secrets.REDHAT_ACTIVATION_KEY_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare the example.repo file
        run: |
          # Replace the baseurl line with the testing repository url
          sed -i "s|baseurl=.*|baseurl=${{ steps.snapshots_and_testing_urls.outputs.rpm_repo_testing_url }}|g" .rpm-packaging/example.repo

      - name: Setup the docker container
        shell: bash
        run: |
          echo "Waiting for the docker container to start"
          # Run the pre-build docker image and mount the needed files
          # Mount the elevation file to avoid downloading it
          # Mount the osm pbf file for the graph build
          # Mount the special ors-config.json file for the rpm container
          docker run -it -d -p 8080:8080 --name ${{ env.CONTAINER_NAME }} \
            -v $(pwd)/ors-api/src/test/files/elevation/srtm_38_03.gh:/opt/openrouteservice/.elevation-cache/srtm_38_03.gh \
            -v $(pwd)/ors-api/src/test/files/heidelberg.osm.gz:/opt/openrouteservice/files/osm-file.osm.gz  \
            -v $(pwd)/.rpm-packaging/ors-config.json:/opt/openrouteservice/config/ors-config.json \
            -v $(pwd)/.rpm-packaging/example.repo:/etc/yum.repos.d/ors.repo \
            ${{ env.IMAGE_NAME }}

      - name: Check the pre-install environment
        shell: bash
        run: |
          ##### Check the pre install environment #####
          echo "Checking the pre install environment"
          bash ${{ github.workspace }}/.rpm-packaging/rhel8_pre_install_check.sh

      - name: Wait for the RPM repo to initialize
        shell: bash
        run: |
          ##### Wait for the RPM repomd.xml to be initialized #####
          echo "Waiting for the RPM repomd.xml to be initialized"
          # Do a curl request to the testing repository and wait for 200 response
          .github/utils/url_check.sh '${{ steps.snapshots_and_testing_urls.outputs.rpm_repo_testing_url }}/repodata/repomd.xml' 200 ${{ env.RPM_TESTING_REPO_WAIT_TIME }}

      - name: Install the rpm package
        shell: bash
        run: |
          ##### Import the GPG key #####
          echo "Importing the GPG key inside the docker container"
          # docker exec -u root ${{ env.CONTAINER_NAME }} rpm --import /tmp/public_key.asc

          ##### Install the rpm package #####
          # Update the yum repository
          docker exec -u root ${{ env.CONTAINER_NAME }} sh -c 'yum update -y'

          echo "Installing the rpm package"
          # Create the missing jws5* rpm packages with fakeprovide
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-runtime
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-tomcat
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-tomcat-native
          docker exec -u root ${{ env.CONTAINER_NAME }} fakeprovide jws5-tomcat-selinux
          # If in debug mode, list the fakeprovide packages
          if [ "${{ github.debug }}" == "true" ]; then
              echo "List the fakeprovide packages"
              docker exec -u root ${{ env.CONTAINER_NAME }} sh -c "ls -sahlS | grep fakeprovide"
          fi
          # Install the rpm package as root with the fakeprovide packages
          docker exec -u root ${{ env.CONTAINER_NAME }} sh -c 'yum install -y fakeprovide-jws5-* openrouteservice-jws5'
          
          ##### Check the post install environment #####
          echo "Checking the post install environment"
          bash ${{ github.workspace }}/.rpm-packaging/rhel8_post_install_check.sh

      - name: Test the graph building
        shell: bash
        run: |
          ##### Start the graph building #####
          # Restart the container to load the new configuration
          docker restart ${{ env.CONTAINER_NAME }}
          
          # echo "Waiting for the docker container to build graphs and return 200"
          .github/utils/url_check.sh '127.0.0.1:8080/ors/v2/health' 200 ${{ env.HEALTH_WAIT_TIME }}
      - name: Print the container logs for debugging
        if: runner.debug == '1'
        shell: bash
        run: |
          ##### Print the container logs for debugging #####
          echo "Print docker logs"
          docker logs ${{ env.CONTAINER_NAME }}

      - name: Uninstall the rpm package
        shell: bash
        run: |
          ##### Uninstall the rpm package #####
          echo "Uninstalling the rpm package"
          docker exec -u root ${{ env.CONTAINER_NAME }} sh -c 'yum remove -y openrouteservice-jws5'
          
          ##### Check the post uninstall environment #####
          echo "Checking the post uninstall environment"
          bash ${{ github.workspace }}/.rpm-packaging/rhel8_post_uninstall_check.sh

      - name: Clean the public GPG key
        run: |
          rm -f ${{ env.GPG_KEY_PATH }}

      - name: Attach RPM package to release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.RPM_PATH }}
          asset_name: ${{ env.RPM_NAME }}
          asset_content_type: application/x-rpm

      - name: Upload the RPM package to the nexus releases rpm registry
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          # Only upload with verbose mode if debug is enabled
          verbose_flag=""
          if [ "${{ github.debug }}" = "true" ]; then
          verbose_flag="-v"
          fi
          curl $verbose_flag -u '${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}' \
              --upload-file '${{ env.RPM_PATH }}' \
              '${{ env.RPM_REPO_RELEASES_URL }}/noarch/${{ env.RPM_NAME }}'
          res=$?
          if test "$res" != "0"; then
            echo "RPM package upload to the nexus rpm registry failed"
            exit 1
          fi
      - name: Upload the snapshot RPM package to the nexus snapshots rpm registry
        # Only upload if this is a push on a release/v7.2.* branch
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/releases/v7.2.')
        run: |
          # Only upload with verbose mode if debug is enabled
          verbose_flag=""
          if [ "${{ github.debug }}" = "true" ]; then
          verbose_flag="-v"
          fi
          # Upload it to a subfolder with the name of the branch
          curl $verbose_flag -u '${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}' \
              --upload-file '${{ env.RPM_PATH }}' \
              '${{ steps.snapshots_and_testing_urls.outputs.rpm_repo_snapshots_url }}/${{ env.RPM_NAME }}'
          res=$?
          if test "$res" != "0"; then
            echo "RPM package upload to the nexus rpm registry failed"
            exit 1
          fi
